### ISSUE TITLE
Stop using dsl in ast tests

### ISSUE THREAD

**Issue by goeran** [goeran/workstation.js#4]
This looses the coupling, and it will be easier to refactor

**Comment by joelmheim** [comment]
Working on this. 

_Sent via Hubroid_

**Comment by goeran** [comment]
Awesome :)

**Comment by joelmheim** [comment]
Fixed. Committed and Pushes. 

_Sent via Hubroid_

**Comment by goeran** [comment]
Great work:)

I'll continue to work on the dsl/ast this evening. I'll also start to dog food it on the SpaceHunter app.
